export const softSkills = [
  "Accountability", "Adaptasi", "Analytical Thinking", "Assertiveness", "Attention to Detail",
  "Bahasa Inggris", "Berbicara di Depan Umum", "Berpikir Kritis", "Classroom Management",
  "Coaching", "Communication Skills", "Confidence", "Continuous Learning", "Critical Thinking",
  "Curiosity", "Customer Service", "Customer-focused", "Delegasi", "Detail-oriented", "Diplomacy",
  "Disiplin", "Empati", "Enthusiasm", "Etos Kerja", "Facilitation", "Fleksibilitas", "Goal-oriented",
  "Humility", "Influence", "Inisiatif", "Innovation", "Integritas", "Kecerdasan Emosional",
  "Kepemimpinan", "Kerja sama tim", "Kerja Tim", "Kerjasama", "Kesabaran", "Kesadaran Budaya",
  "Keterampilan Interpersonal", "Keterampilan Penjualan", "Keterampilan Presentasi", "Kolaborasi",
  "Komunikasi", "Komunikasi efektif", "Koordinasi", "Kreativitas", "Layanan Pelanggan", "Leadership",
  "Manajemen Stres", "Manajemen Waktu", "Mediation", "Mendengarkan Aktif", "Mentoring", "Motivasi Diri",
  "Multitasking", "Negosiasi", "Networking", "Open-mindedness", "Organisasi", "Pemecahan Masalah",
  "Pengambilan Keputusan", "Perhatian terhadap Detail", "Persuasion", "Positive Attitude", "Presentasi",
  "Proaktif", "Problem solving", "Process-oriented", "Profesionalisme", "Public Speaking", "Punctuality",
  "Quality-focused", "Reliability", "Resilience", "Resolusi Konflik", "Resourcefulness", "Results-driven",
  "Self-motivated", "Strategic Thinking", "Tact", "Tanggung Jawab", "Teamwork", "Time Management",
  "Visionary", "Work Ethic"
];

export const hardSkills = [
  "3D Modeling", "3D Rendering", "A/B Testing", "Account Management", "Administrasi Jaringan",
  "Airflow", "Akuntansi", "Analisis Bisnis", "Analisis Data", "Analisis Keuangan", "Analisis Laporan Keuangan",
  "Analisis Statistik", "Android Development", "Angular", "Animasi", "Apache Hadoop", "Apache Kafka",
  "Apache Spark", "App Store Optimization", "Application Security", "Assessment Design", "Audio Editing",
  "Audit", "AWS", "B2B Sales", "B2C Sales", "Bash", "Big Data", "Brand Management", "Branding", "Budgeting",
  "Business Development", "Business Intelligence", "C#", "C++", "CAD", "Campaign Management", "Candidate Sourcing",
  "Chemical Engineering", "CI/CD", "Civil Engineering", "Clinical Documentation", "Cloud Security", "Cold Calling",
  "Color Grading", "Compensation & Benefits", "Competitor Analysis", "Compliance", "Computer Vision",
  "Content Marketing", "Contract Drafting", "Contract Review", "Conversion Optimization", "Copywriting",
  "Cordova", "Corporate Law", "Cryptography", "CSS", "Customer Insights", "Customs Clearance", "Dart",
  "Data Engineering", "Data Mining", "Data Science", "Data Visualization", "Data Warehousing", "Deep Learning",
  "Demand Planning", "Desain Grafis", "Desain UI/UX", "Desain Web", "Digital Illustration", "Distribution Management",
  "Django", "Docker", "Due Diligence", "E-commerce Management", "E-learning Development", "Editing Video",
  "Educational Technology", "Electrical Engineering", "Electronic Health Records", "Email Marketing",
  "Employee Relations", "Ethical Hacking", "ETL", "Event Management", "Event Planning", "Express.js",
  "Firewall Management", "Flask", "Flutter", "Food & Beverage Service", "Forecasting", "Fotografi",
  "Freight Forwarding", "Front Office Operations", "GDPR Compliance", "Go", "Google Cloud Platform",
  "Growth Hacking", "Healthcare Administration", "Hospitality Management", "Hotel Management",
  "Housekeeping Management", "HR Analytics", "HTML", "IDS/IPS", "Illustration", "Import/Export",
  "Incident Response", "Industrial Engineering", "Influencer Marketing", "Information Architecture",
  "Instructional Design", "Intellectual Property", "Interaction Design", "Interviewing", "Inventory Management",
  "Ionic", "iOS Development", "ISO 27001", "Java", "JavaScript", "Jetpack Compose", "Keamanan Siber",
  "Keras", "Kotlin", "Kreator Konten", "Kubernetes", "Labor Law", "Laboratory Skills", "Laravel",
  "Layout Design", "Lead Generation", "Lean Manufacturing", "Learning Management Systems", "Legal Research",
  "Legal Writing", "Lesson Planning", "Linux", "Litigation", "Logistics Coordination", "Machine Learning",
  "Manajemen Hubungan Pelanggan", "Manajemen Inventaris", "Manajemen Kualitas", "Manajemen Operasional",
  "Manajemen Proyek", "Manajemen Rantai Pasokan", "Manajemen Risiko", "Market Research", "Marketing Automation",
  "Marketplace Management", "Mechanical Engineering", "Medical Billing", "Medical Coding", "Medical Terminology",
  "Merchandising", "Microsoft Azure", "Mobile Analytics", "Mobile UI Design", "MongoDB", "Monitoring",
  "Motion Graphics", "MySQL", "Natural Language Processing", "Network Security", "Next.js", "Node.js", "NoSQL",
  "NumPy", "Nursing Care", "Onboarding", "Online Teaching", "Order Fulfillment", "Organizational Development",
  "Pandas", "Patient Care", "Payroll Management", "Pemasaran Digital", "Pembukuan", "Penetration Testing",
  "Pengembangan Android", "Pengembangan Bisnis", "Pengembangan iOS", "Pengembangan Kurikulum",
  "Pengujian Perangkat Lunak", "Penulisan Konten", "Penulisan Teknis", "Perencanaan Anggaran",
  "Perencanaan Strategis", "Performance Management", "Performance Marketing", "Perpajakan", "Pharmacy Management",
  "PHP", "PLC Programming", "PostgreSQL", "PowerShell", "Predictive Analytics", "Pricing Strategy",
  "Process Improvement", "Procurement", "Product Listing", "Product Marketing", "Project Estimation",
  "Prototyping", "Python", "PyTorch", "Quality Assurance", "Quality Control", "React", "React Native",
  "Recruitment", "Redis", "Regulatory Affairs", "Reservation Systems", "Riset Pasar", "Ruby", "Rust",
  "Sales Forecasting", "Sales Strategy", "SCADA", "Scikit-learn", "Security Auditing", "SEM", "SEO",
  "Shell Scripting", "SIEM", "Six Sigma", "Social Media Marketing", "Spring Boot", "SQL", "Statistical Modeling",
  "Strategic Planning", "Supply Chain Management", "Swift", "SwiftUI", "Talent Acquisition", "Technical Drawing",
  "TensorFlow", "Threat Intelligence", "Time Series Analysis", "Tour Guiding", "Training & Development",
  "Transportation Management", "Travel Planning", "Tutoring", "TypeScript", "Typography", "Unix",
  "Usability Testing", "User Research", "Vendor Management", "Video Production", "Vue.js", "Vulnerability Assessment",
  "Warehouse Management", "Windows Server", "Wireframing", "Xamarin"
];

export const softwareSkills = [
  "3ds Max", "Adobe After Effects", "Adobe Captivate", "Adobe Creative Suite", "Adobe Illustrator",
  "Adobe InDesign", "Adobe Photoshop", "Adobe Premiere Pro", "Adobe XD", "Affinity Designer", "Ansible",
  "Apache", "Articulate Storyline", "Asana", "AutoCAD", "Blender", "Bukalapak", "Canva", "Capture One",
  "CATIA", "Chef", "Cinema 4D", "CircleCI", "CorelDRAW", "CRM", "Datadog", "DaVinci Resolve", "Discord",
  "Docker Desktop", "Eclipse", "ELK Stack", "ERP", "Excel", "Facebook Ads Manager", "Figma", "Final Cut Pro",
  "Firebase", "Framer", "Git", "GitHub", "GitHub Actions", "GitLab", "GitLab CI", "Google Ads", "Google Analytics",
  "Google Docs", "Google Sheets", "Google Workspace", "Grafana", "HRIS", "HubSpot", "IntelliJ IDEA", "InVision",
  "Jenkins", "Jira", "Lazada", "Lightroom", "Magento", "Mailchimp", "MATLAB", "Maya", "Microsoft Excel",
  "Microsoft Office", "Microsoft PowerPoint", "Microsoft Teams", "Microsoft Word", "Moodle", "New Relic", "Nginx",
  "Oracle ERP", "Point-of-sale (POS)", "Postman", "Power BI", "PrestaShop", "Principle", "Procreate", "Prometheus",
  "ProtoPie", "Puppet", "QuickBooks", "R Studio", "Revit", "Salesforce", "SAP", "Shopee", "Shopify", "Simulink",
  "Sketch", "SketchUp", "Slack", "SolidWorks", "Splunk", "SPSS", "STATA", "Substance Painter", "Tableau",
  "Terraform", "Tokopedia", "Travis CI", "Trello", "Vagrant", "VirtualBox", "Visual Studio Code", "VMware",
  "WooCommerce", "WordPress", "ZBrush", "Zoom"
];
