import { Section } from "@/types/builder";

export const COMPLETE_PORTFOLIO_TEMPLATE: Section[] = [
  {
    id: "global-settings",
    type: "CANVAS_SETTINGS",
    order: -1,
    isActive: true,
    config: { bgType: "solid", bgColor: "#09090b" }, // Dark background by default
    elements: [],
  },
  // 1. HERO
  {
    id: "hero-section",
    type: "SECTION",
    order: 1,
    isActive: true,
    config: {
      bgColor: "transparent",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 160,
      paddingBottom: 120,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "flexbox",
      direction: "col",
      align: "center",
      gap: 24,
    },
    elements: [
      {
        id: "hero-badge",
        type: "BADGE",
        config: {
          text: "TERSEDIA UNTUK FREELANCE",
          style: "outline",
          textColor: "#10b981",
          borderColor: "#10b981",
          borderRadius: 9999,
          align: "center",
        },
      },
      {
        id: "hero-title",
        type: "HEADING",
        config: {
          text: "Membangun Pengalaman Digital yang Luar Biasa",
          fontSize: 64,
          fontWeight: "900",
          textColor: "#ffffff",
          align: "center",
          lineHeight: 1.1,
          letterSpacing: -1,
        },
      },
      {
        id: "hero-subtitle",
        type: "TEXT",
        config: {
          text: "Saya adalah seorang Developer dan Desainer yang fokus menciptakan solusi elegan untuk masalah yang kompleks.",
          fontSize: 20,
          textColor: "#a1a1aa",
          align: "center",
          widthType: "custom",
          customWidth: 600,
          margin: "0 auto",
        },
      },
      {
        id: "hero-btn-group",
        type: "COLUMN",
        config: {
          sizing: "fit",
          width: "fit-content",
          direction: "row",
          gap: 16,
        },
        elements: [
          {
            id: "btn-primary",
            type: "BUTTON",
            config: {
              text: "Lihat Portofolio",
              style: "primary",
              bgColor: "#3b82f6",
              textColor: "#ffffff",
              borderRadius: 8,
              paddingTop: 14,
              paddingBottom: 14,
              paddingLeft: 28,
              paddingRight: 28,
              fontWeight: "600",
            },
          },
          {
            id: "btn-secondary",
            type: "BUTTON",
            config: {
              text: "Hubungi Saya",
              style: "outline",
              borderColor: "#3f3f46",
              textColor: "#ffffff",
              borderRadius: 8,
              paddingTop: 14,
              paddingBottom: 14,
              paddingLeft: 28,
              paddingRight: 28,
              fontWeight: "600",
            },
          },
        ],
      },
    ],
  },
  // 2. TENTANG SAYA
  {
    id: "about-section",
    type: "SECTION",
    order: 2,
    isActive: true,
    config: {
      bgColor: "#121214",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "grid",
      columns: 2,
      gap: 40,
      alignItems: "center",
    },
    elements: [
      {
        id: "about-image-col",
        type: "COLUMN",
        config: { sizing: "auto" },
        elements: [
          {
            id: "about-image",
            type: "IMAGE",
            config: {
              url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
              aspectRatio: "1/1",
              borderRadius: 24,
              objectFit: "cover",
            },
          },
        ],
      },
      {
        id: "about-content-col",
        type: "COLUMN",
        config: { sizing: "auto", direction: "col", gap: 20 },
        elements: [
          {
            id: "about-label",
            type: "BADGE",
            config: {
              text: "TENTANG SAYA",
              style: "solid",
              bgColor: "#27272a",
              textColor: "#e4e4e7",
              borderRadius: 4,
            },
          },
          {
            id: "about-heading",
            type: "HEADING",
            config: {
              text: "Berdedikasi untuk menciptakan produk digital yang berdampak.",
              fontSize: 40,
              fontWeight: "800",
              textColor: "#ffffff",
              lineHeight: 1.2,
            },
          },
          {
            id: "about-text",
            type: "TEXT",
            config: {
              text: "Selama lebih dari 5 tahun, saya telah membantu berbagai perusahaan rintisan hingga perusahaan berskala besar dalam merancang dan mengembangkan aplikasi web yang cepat, responsif, dan mudah digunakan.",
              fontSize: 16,
              textColor: "#a1a1aa",
              lineHeight: 1.6,
            },
          },
        ],
      },
    ],
  },
  // 3. SKILL
  {
    id: "skill-section",
    type: "SECTION",
    order: 3,
    isActive: true,
    config: {
      bgColor: "transparent",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "flexbox",
      direction: "col",
      align: "center",
      gap: 40,
    },
    elements: [
      {
        id: "skill-header-col",
        type: "COLUMN",
        config: { sizing: "fit", direction: "col", gap: 16, align: "center" },
        elements: [
          {
            id: "skill-heading",
            type: "HEADING",
            config: {
              text: "Keahlian Saya",
              fontSize: 48,
              fontWeight: "800",
              textColor: "#ffffff",
              align: "center",
            },
          },
          {
            id: "skill-desc",
            type: "TEXT",
            config: {
              text: "Teknologi dan alat yang saya kuasai",
              fontSize: 18,
              textColor: "#a1a1aa",
              align: "center",
            },
          },
        ],
      },
      {
        id: "skill-list",
        type: "CATEGORY_LIST",
        config: {
          layout: "grid",
          columns: 4,
          gap: 20,
          cardBgColor: "#18181b",
          cardBorderRadius: 16,
          cardBorderColor: "#27272a",
          cardPadding: 24,
          alignText: "center",
          items: [
            { id: "s1", title: "Frontend Development", subtitle: "React, Next.js, Vue" },
            { id: "s2", title: "Backend Development", subtitle: "Node.js, Go, Python" },
            { id: "s3", title: "UI/UX Design", subtitle: "Figma, Adobe XD" },
            { id: "s4", title: "DevOps", subtitle: "Docker, AWS, CI/CD" },
          ],
        },
      },
    ],
  },
  // 4. LAYANAN
  {
    id: "services-section",
    type: "SECTION",
    order: 4,
    isActive: true,
    config: {
      bgColor: "#0f0f12",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "flexbox",
      direction: "col",
      gap: 48,
    },
    elements: [
      {
        id: "services-heading",
        type: "HEADING",
        config: {
          text: "Layanan Unggulan",
          fontSize: 48,
          fontWeight: "800",
          textColor: "#ffffff",
          align: "left",
        },
      },
      {
        id: "services-list",
        type: "PRODUCT_LIST", // Menggunakan product list karena desain card-nya pas
        config: {
          layout: "grid",
          columns: 3,
          gap: 24,
          cardBgColor: "#18181b",
          cardBorderRadius: 16,
          cardBorderColor: "#27272a",
          cardPadding: 24,
          showPrice: false,
          items: [
            { id: "srv1", name: "Web Development", description: "Pembuatan website company profile, e-commerce, hingga web app kustom." },
            { id: "srv2", name: "Mobile App Development", description: "Pengembangan aplikasi iOS dan Android native maupun hybrid." },
            { id: "srv3", name: "UI/UX Design", description: "Desain antarmuka yang estetis dan user experience yang optimal." },
          ],
        },
      },
    ],
  },
  // 5. PORTOFOLIO
  {
    id: "portfolio-section",
    type: "SECTION",
    order: 5,
    isActive: true,
    config: {
      bgColor: "transparent",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "flexbox",
      direction: "col",
      gap: 40,
    },
    elements: [
      {
        id: "portfolio-header-col",
        type: "COLUMN",
        config: { sizing: "fit", direction: "col", gap: 16 },
        elements: [
          {
            id: "portfolio-heading",
            type: "HEADING",
            config: {
              text: "Karya Terbaru",
              fontSize: 48,
              fontWeight: "800",
              textColor: "#ffffff",
            },
          },
          {
            id: "portfolio-desc",
            type: "TEXT",
            config: {
              text: "Beberapa proyek terbaik yang pernah saya kerjakan.",
              fontSize: 18,
              textColor: "#a1a1aa",
            },
          },
        ],
      },
      {
        id: "portfolio-grid",
        type: "GALLERY",
        config: {
          layout: "grid",
          columns: 2,
          gap: 24,
          borderRadius: 16,
          aspectRatio: "16/9",
          items: [
            { id: "p1", url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80", caption: "E-Commerce Dashboard" },
            { id: "p2", url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80", caption: "Finance Mobile App" },
            { id: "p3", url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80", caption: "Corporate Landing Page" },
            { id: "p4", url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80", caption: "SaaS Platform" },
          ],
        },
      },
    ],
  },
  // 6. PENGALAMAN
  {
    id: "experience-section",
    type: "SECTION",
    order: 6,
    isActive: true,
    config: {
      bgColor: "#121214",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "flexbox",
      direction: "col",
      align: "center",
      gap: 48,
    },
    elements: [
      {
        id: "exp-heading",
        type: "HEADING",
        config: {
          text: "Pengalaman Kerja",
          fontSize: 48,
          fontWeight: "800",
          textColor: "#ffffff",
          align: "center",
        },
      },
      {
        id: "exp-list",
        type: "CATEGORY_LIST",
        config: {
          layout: "list",
          columns: 1,
          gap: 16,
          cardBgColor: "#18181b",
          cardBorderRadius: 12,
          cardBorderColor: "#27272a",
          cardPadding: 24,
          alignText: "left",
          items: [
            { id: "e1", title: "Senior Frontend Engineer - Tokopedia", subtitle: "2021 - Sekarang | Memimpin tim UI untuk platform seller." },
            { id: "e2", title: "Fullstack Developer - Gojek", subtitle: "2018 - 2021 | Mengembangkan sistem internal finance." },
            { id: "e3", title: "Web Designer - Freelance", subtitle: "2016 - 2018 | Mengerjakan puluhan website klien internasional." },
          ],
        },
      },
    ],
  },
  // 7. STATISTIK
  {
    id: "stats-section",
    type: "SECTION",
    order: 7,
    isActive: true,
    config: {
      bgColor: "#2563eb", // Blue-600
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 80,
      paddingBottom: 80,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "flexbox",
      direction: "col",
      align: "center",
    },
    elements: [
      {
        id: "stats-list",
        type: "CATEGORY_LIST",
        config: {
          layout: "grid",
          columns: 4,
          gap: 20,
          cardBgColor: "transparent",
          cardBorderRadius: 0,
          cardBorderColor: "transparent",
          cardPadding: 0,
          alignText: "center",
          items: [
            { id: "st1", title: "50+", subtitle: "Proyek Selesai" },
            { id: "st2", title: "30+", subtitle: "Klien Puas" },
            { id: "st3", title: "5", subtitle: "Tahun Pengalaman" },
            { id: "st4", title: "10", subtitle: "Penghargaan" },
          ],
        },
      },
    ],
  },
  // 8. TEKNOLOGI
  {
    id: "tech-section",
    type: "SECTION",
    order: 8,
    isActive: true,
    config: {
      bgColor: "transparent",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "flexbox",
      direction: "col",
      align: "center",
      gap: 40,
    },
    elements: [
      {
        id: "tech-heading",
        type: "HEADING",
        config: {
          text: "Stack Teknologi",
          fontSize: 32,
          fontWeight: "700",
          textColor: "#ffffff",
          align: "center",
        },
      },
      {
        id: "tech-brands",
        type: "GALLERY",
        config: {
          layout: "grid",
          columns: 6,
          gap: 40,
          aspectRatio: "1/1",
          objectFit: "contain",
          items: [
            { id: "t1", url: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" },
            { id: "t2", url: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Nextjs-logo.svg" },
            { id: "t3", url: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg" },
            { id: "t4", url: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg" },
            { id: "t5", url: "https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg" },
            { id: "t6", url: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg" },
          ],
        },
      },
    ],
  },

  {
    id: "contact-section",
    type: "SECTION",
    order: 10,
    isActive: true,
    config: {
      bgColor: "transparent",
      contentWidth: "boxed",
      maxWidth: "1200px",
      paddingTop: 100,
      paddingBottom: 100,
      paddingLeft: 40,
      paddingRight: 40,
      layout: "grid",
      columns: 2,
      gap: 60,
      alignItems: "start",
    },
    elements: [
      {
        id: "contact-info-col",
        type: "COLUMN",
        config: { sizing: "auto", direction: "col", gap: 24 },
        elements: [
          {
            id: "contact-heading",
            type: "HEADING",
            config: {
              text: "Mari Bekerja Sama!",
              fontSize: 48,
              fontWeight: "800",
              textColor: "#ffffff",
            },
          },
          {
            id: "contact-text",
            type: "TEXT",
            config: {
              text: "Punya ide proyek hebat? Jangan ragu untuk menghubungi saya. Saya selalu terbuka untuk mendiskusikan pekerjaan freelance atau peluang kolaborasi.",
              fontSize: 18,
              textColor: "#a1a1aa",
            },
          },
          {
            id: "contact-email-btn",
            type: "BUTTON",
            config: {
              text: "hello@portotree.com",
              style: "outline",
              borderColor: "#3f3f46",
              textColor: "#ffffff",
              borderRadius: 8,
              paddingTop: 14,
              paddingBottom: 14,
              paddingLeft: 24,
              paddingRight: 24,
              fontWeight: "600",
            },
          },
        ],
      },
      {
        id: "contact-form-col",
        type: "COLUMN",
        config: { sizing: "auto", direction: "col", gap: 16, bgColor: "#121214", borderRadius: 24, padding: 40, borderColor: "#27272a", borderType: "solid", borderWidth: 1 },
        elements: [
          {
            id: "form-heading",
            type: "HEADING",
            config: {
              text: "Kirim Pesan",
              fontSize: 24,
              fontWeight: "700",
              textColor: "#ffffff",
            },
          },
          {
            id: "form-name",
            type: "TEXT",
            config: { text: "Nama Anda...", fontSize: 14, textColor: "#71717a" },
          },
          {
            id: "form-email",
            type: "TEXT",
            config: { text: "Email Anda...", fontSize: 14, textColor: "#71717a" },
          },
          {
            id: "form-msg",
            type: "TEXT",
            config: { text: "Pesan Anda...", fontSize: 14, textColor: "#71717a" },
          },
          {
            id: "form-submit",
            type: "BUTTON",
            config: {
              text: "Kirim Sekarang",
              style: "primary",
              bgColor: "#3b82f6",
              textColor: "#ffffff",
              borderRadius: 8,
              paddingTop: 14,
              paddingBottom: 14,
              width: "100%",
            },
          },
        ],
      },
    ],
  },
];
